server:
  port: 8083

spring:
  application:
    name: heima-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
#  data:
#    redis:
#      host: 192.168.31.222
#logging:
#  level:
#    org.springframework.ai: debug
#    com.itheima.ai: debug